# Generated by Django 3.2.9 on 2021-11-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBookStore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
