# Generated by Django 3.2.9 on 2021-11-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBookStore', '0003_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubyear',
            field=models.DateField(),
        ),
    ]
