# Generated by Django 3.2.9 on 2021-11-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBookStore', '0005_auto_20211129_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(default=0, max_length=13, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('FICT', 'Fiction'), ('NFICT', 'Nonfiction'), ('CL', 'Classic'), ('BI', 'Biography'), ('TECH', 'Technology')], max_length=20),
        ),
    ]
