# Generated by Django 3.2.9 on 2021-11-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBookStore', '0007_alter_book_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
