# Generated by Django 3.2.9 on 2021-11-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBookStore', '0008_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author Name', models.CharField(default='Enter Author Name', max_length=25)),
            ],
        ),
    ]
